Scrolltopia.Web/Models/ControllerDemoCollection.cs
using System.Collections.Generic;

namespace Scrolltopia.Web.Models
{
    public class ControllerDemoCollection
    {
        public string ControllerName { get; set; }
        public IList<DemoSection> Demos { get; set; }
    }
}

Scrolltopia.Web/Models/Demo.cs
namespace Scrolltopia.Web.Models
{
    public class Demo
    {
        public string Title { get; set; }
        public string ActionName { get; set; }
    }
}

Scrolltopia.Web/Models/DemoSection.cs
using System.Collections.Generic;

namespace Scrolltopia.Web.Models
{
    public class DemoSection
    {
        public string Title { get; set; }
        public IList<Demo> Demos { get; set; }
    }
}

Scrolltopia.Web/Models/ERender.cs
namespace Scrolltopia.Web.Models
{
    public enum ERender
    {
        Content,
        Menu
    }
}

Scrolltopia.Web/ViewModels/Render.cs
using Scrolltopia.Web.Models;

namespace Scrolltopia.Web.ViewModels
{
    /// <summary>
    /// Wraps any Model and provides a mode (<see cref="ERender"/>)
    /// to decide how the model should be rendered.
    /// E.g. as content or menu
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public class Render<T>
    {
        /// <summary>
        /// Initializes Render with a model.
        /// </summary>
        /// <param name="model">The model that should be rendered</param>
        /// <returns>new instance of Render</returns>
        public static Render<T> Model(T model)
        {
            return new Render<T>
            {
                Content = model
            };
        }

        /// <summary>
        /// Instance of the model that should be rendered
        /// </summary>
        public T Content { get; set; }

        /// <summary>
        /// The current render mode used to decide which
        /// template should be applied to the model
        /// </summary>
        public ERender RenderMode { get; private set; }

        /// <summary>
        /// Configures the render mode for the model
        /// </summary>
        /// <param name="renderMode">the desired render mode</param>
        /// <returns>instance of Render</returns>
        public Render<T> As(ERender renderMode)
        {
            RenderMode = renderMode;
            return this;
        }
    }
}

Scrolltopia.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Scrolltopia.Web.Controllers
{
    public class HomeController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }
    }
}

Scrolltopia.Web/Controllers/IscrollController.cs
using System.Web.Mvc;
using Scrolltopia.Web.DemoRepositories;

namespace Scrolltopia.Web.Controllers
{
    public class IscrollController : Controller
    {
        private readonly IscrollDemos _demos;

        public IscrollController()
        {
            _demos = new IscrollDemos();
        }

        public ActionResult Index()
        {
            return View(_demos.GetAll());
        }

        public ViewResult MinimalSetup()
        {
            return View();
        }

        public ViewResult Scrollbar()
        {
            return View();
        }

        public ViewResult FadingScrollbar()
        {
            return View();
        }

        public ViewResult InteractiveScrollbar()
        {
            return View();
        }

        public ActionResult ShrinkedScrollbar()
        {
            return View();
        }

        public ActionResult ClickableElements()
        {
            return View();
        }



        public ActionResult ResizingContainer()
        {
            return View();
        }

        public ActionResult ResizingScrollingContent()
        {
            return View();
        }

        public ActionResult Deceleration()
        {
            return View();
        }

        public ActionResult TriggeringControls()
        {
            return View();
        }

        public ActionResult AnimatedScrollingContent()
        {
            return View();
        }

        public ActionResult HandleScrollEvents()
        {
            return View();
        }
    }
}

Scrolltopia.Web/Controllers/NanoScrollerController.cs
using System.Web.Mvc;

namespace Scrolltopia.Web.Controllers
{
    public class NanoScrollerController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }
    }
}

Scrolltopia.Web/Controllers/SimpleBarController.cs
using System.Web.Mvc;
using Scrolltopia.Web.DemoRepositories;

namespace Scrolltopia.Web.Controllers
{
    public class SimplebarController : Controller
    {
        private readonly SimplebarDemos _demos;

        public SimplebarController()
        {
            _demos = new SimplebarDemos();
        }

        public ViewResult Index()
        {
            return View(_demos.GetAll());
        }

        public ViewResult MinimalSetup()
        {
            return View();
        }

        public ViewResult Scrollbar()
        {
            return View();
        }

        public ViewResult TriggeringControls()
        {
            return View();
        }

        public ViewResult ScrollInAbsoultePositionedContainers()
        {
            return View();
        }

        public ViewResult CustomizingScrollbar()
        {
            return View();
        }

        public ViewResult Ie8CssOptimization()
        {
            return View();
        }
    }
}

Scrolltopia.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Welcome | Scrolltopia";
}

<div class="container">
    <div class="well">
        <h1>Welcome to Scrolltopia</h1>
        <p class="lead">
            This page presents a showcase evaluating different scrolling frameworks.
            For the moment you have access to different samples using
            @Html.ActionLink("iScroll", "Index", "Iscroll") and @Html.ActionLink("simplebar", "Index", "Simplebar").
        </p>
    </div>
</div>

Scrolltopia.Web/Views/Iscroll/AnimatedScrollingContent.cshtml
@{
    ViewBag.Title = "Animated scrolling content | iScroll";
}

<div class="container">
    <div class="row">
        <h1>Animated scrolling content</h1>
        <p>
            Hovering the picture inside the sample will scale it to the half of its width and height
        </p>
        <div class="alert alert-warning">
            <strong>IScroll will not refresh!</strong>
            Unfortunately IScroll is not aware of animations. It does not observe it's scrolling content.
        </div>
         <hr>
    </div>
    <div class="row">

        <section class="sample">

            <div class="iscroll-container">
                <div class="scrolling-content">
                    <p class="mdr-tower scale-to-the-half"></p>
                </div>
            </div>

        </section>
        
    </div>
    <div class="row">
        <h2>Configuration</h2>
        <pre>
            {
                scrollbars: true,
                mouseWheel: true
            }   
        </pre>
    </div>
</div>

@section Script
{
    <script type="text/javascript">
        (function () {
            'use strict';

            var myScroll = new IScroll('.iscroll-container', {
                scrollbars: true,
                mouseWheel: true
            });
        }());
     </script>
}

Scrolltopia.Web/Views/Iscroll/ClickableElements.cshtml
@{
    ViewBag.Title = "Scrollbar | iScroll";
}

<div class="container">
    <div class="row">
        <h1>Handle click event when iScroll is disabled</h1>
        <p>
            This sample is used to see if iScroll handles click-evevnts even when it is disabled.
        </p>
        <div class="alert alert-danger">
            <span class="glyphicon glyphicon-exclamation-sign"></span> The upper container's link is not clickable since the browser emulator is enabled.
            We experienced strange behavior setting up Kindle Fire HDX.
        </div>
    </div>
    <div class="row">

        <section class="sample">

            <div id="container-having-iscroll-enabled" class="iscroll-container">
                <p class="height-of-450-pixels">
                    Just scroll & click!
                    <br>
                    <a href="http://woiwode.info/blog" target="_blank">woiwode.info/blog</a>
                </p>
            </div>

        </section>

        <hr>

        <section class="sample">

            <div id="container-having-iscroll-disabled" class="iscroll-container">
                <p class="height-of-450-pixels">
                    Scrolling is disabled here! Click events should still work.
                    <br>
                    <a href="http://woiwode.info/blog" target="_blank">woiwode.info/blog</a>
                </p>
            </div>

        </section>

    </div>
    <div class="row">
        <h2>Configuration</h2>
        <pre>
            {
                scrollbars: true,
                mouseWheel: true
            }   
        </pre>
    </div>
</div>

@section Script
{
    <script type="text/javascript">
        (function () {
            'use strict';

            var enabledIscroll = new IScroll('#container-having-iscroll-enabled', {
                mouseWheel: true,
                scrollbars: true
            });

            var disabledIscroll = new IScroll('#container-having-iscroll-disabled', {
                mouseWheel: true,
                scrollbars: true
            });

            disabledIscroll.disable();
        }());
     </script>
}

Scrolltopia.Web/Views/Iscroll/Deceleration.cshtml
@{
    ViewBag.Title = "Decelerating scrollbar | iScroll";
}


<div class="container">
    <div class="row">
        <h1>Decelerating scrollbar</h1>
        <p>
            Deceleration configures the duration of scrolling animation.
        </p>
        <div class="alert alert-info">
            <span class="glyphicon glyphicon-info-sign"></span> The smaller the configured <code>deceleration</code> the longer the animation takes.
        </div>
        <div class="alert alert-warning">
            <span class="glyphicon glyphicon-warning-sign"></span> It seems that this option has no impact when mouse wheel is used.
        </div>

        <hr>
    </div>
    <div class="row">

        <section class="sample">

            <div class="iscroll-container ">
                <p class="height-of-450-pixels">I should scroll</p>
            </div>

        </section>
        
    </div>
    <div class="row">
        <h2>Configuration</h2>
        <pre>
            {
                scrollbars: true,
                mouseWheel: true,
                // default: 0.0002
                deceleration: 0.00002
            }   
        </pre>
    </div>
</div>

@section Script
{
    <script type="text/javascript">
        (function () {
            'use strict';

            var myScroll = new IScroll('.iscroll-container', {
                scrollbars: true,
                mouseWheel: true,
                deceleration: 0.00002
        });
        }());
     </script>
}

Scrolltopia.Web/Views/Iscroll/FadingScrollbar.cshtml
@{
    ViewBag.Title = "Fading scrollbar | iScroll";
}

<div class="container">
    <div class="row">
        <h1>Fading scrollbar</h1>
        <p>
            This sample displays the scrollbar only when the user scrolls.
        </p>
    </div>
    <div class="row">

        <section class="sample">

            <div class="iscroll-container">
                <p class="height-of-450-pixels">I should scroll</p>
            </div>

        </section>

    </div>
    <div class="row">
        <h2>Configuration</h2>
        <pre>
            {
                scrollbars: true,
                fadeScrollbars: true,
                mouseWheel: true
            }   
        </pre>
    </div>
</div>

@section Script
{
    <script type="text/javascript">
        (function () {
            'use strict';

            var myscroll = new IScroll('.iscroll-container', {
                scrollbars: true,
                fadeScrollbars: true,
                mouseWheel: true
            });
        }());
     </script>
}

Scrolltopia.Web/Views/Iscroll/HandleScrollEvents.cshtml
@{
    ViewBag.Title = "Handle scroll events | iScroll";
}


<div class="container">
    <div class="row">
        <h1>Handle scroll events <small><a href="http://iscrolljs.com/#custom-events">available events</a></small></h1>
        <div>
            This sample listens to the <code>scroll</code> event.
            When it is fired a gradient should be added at the top/bottom of the scrolling-container.
        </div>

        <div class="alert alert-warning">
            <span class="glyphicon glyphicon-warning-sign"></span> If you want to use the <code>scroll</code> event
            <code>iscroll-probe.js</code> has to be used. The documentation says <code>scroll</code> needs a lot of performance.
            To make use of <code>scroll</code> the configuration property <code>probeType</code> hast to be set.
        </div>

        <hr>
    </div>

    <div class="row">

        <section class="sample plain">

            <div class="scroll-gradient">
                <div class="scroll-gradient-top"></div>
            </div>

            <div class="iscroll-container">
                <div class="scrolling-content">
                    @LoremIpsum.InsertParagraphs(4)
                </div>
            </div>

            <div class="scroll-gradient">
                <div class="scroll-gradient-bottom"></div>
            </div>

        </section>

    </div>
    <div class="row">
        <h2>Configuration</h2>
        <pre class="reset-styles">
            <code class="javascript">
{
    // Allowed values 1..3 -> 3 means highes possible raise of events
    probeType: 2,
    scrollbars: true,
    mouseWheel: true
}  
            </code>
        </pre>

        <h2>Used Markup</h2>
        <pre class="reset-styles">
            <code class="html">
&lt;div class="scroll-gradient-top"&gt;&lt;/div&gt; &lt;!-- this div is wrapped by scroll-gradient --&gt;
&lt;div class="iscroll-container"&gt;
    &lt;div class="scrolling-content"&gt;
        ...
    &lt;/div&gt;
&lt;/div&gt;
&lt;div class="scroll-gradient-bottom"&gt;&lt;/div&gt; &lt;!-- this div is wrapped by scroll-gradient --&gt;
            </code>
        </pre>
    </div>
</div>

@section Script
{
    <script type="text/javascript">
        (function () {
            'use strict';

            var gradientTop = $('.scroll-gradient-top');
            var gradientBottom = $('.scroll-gradient-bottom');

            var myScroll = new IScroll('.iscroll-container', {
                probeType: 3,
                scrollbars: true,
                mouseWheel: true
            });

            handleGradienVisibility(0, 0, myScroll.maxScrollY);

            myScroll.on('scroll', raiseScrollActionStarted);

            function raiseScrollActionStarted() {
                var currentY = myScroll.y;
                var minScrollY = 0;
                var maxScrollY = myScroll.maxScrollY;

                handleGradienVisibility(currentY, minScrollY, maxScrollY);
            }

            function handleGradienVisibility(currentY, minScrollY, maxScrollY) {

                if (currentY > maxScrollY + gradientTop.height())
                    gradientBottom.fadeIn();
                else
                    gradientBottom.fadeOut();

                if (currentY < minScrollY - gradientBottom.height())
                    gradientTop.fadeIn();
                else
                    gradientTop.fadeOut();
            };
        }());
     </script>
}

Scrolltopia.Web/Views/Iscroll/Index.cshtml
@using Scrolltopia.Web.Models
@using Scrolltopia.Web.ViewModels
@model Scrolltopia.Web.Models.ControllerDemoCollection

@{
    ViewBag.Title = "iScroll | Scrolltopia";
}

<div class="container">
    <h1>iScroll showcase <small><a href="http://iscrolljs.com/" target="_blank">Project site</a></small></h1>

    <h2 id="no-ie8-support">No IE8 support</h2>
    <div class="alert alert-warning">
        <span class="glyphicon glyphicon-warning-sign"></span>&nbsp;
        It turns out taht iScroll does not support IE8 (<a href="https://github.com/cubiq/iscroll/pull/436" target="_blank">see issue</a>).
        There are some libraries hacking the support for IE8.
        Trying <a href="https://github.com/4alexandr/iscroll5-ie8/blob/master/iscroll5-ie8.js">iscroll5-ie8</a> does not work.
    </div>

    <h2>Prerequisits</h2>
    <div>
        To get iScroll to work it is importand to setup some css styles. Otherwise you will experience an unexpected scrolling behavior.
        The following sample shows the style of the wrapping container which will be passed to iScroll.
        <ul>
            <li>The container has to define <code>height</code> or <code>max-height</code>.</li>
            <li><code>overflow:hidden</code> has to be set.</li>
            <li>The container needs to have <code>postion-relative</code>.</li>
        </ul>
    </div>
    <pre class="reset-styles">
    <code class="css">
.iscroll-container {
    height:   200px;
    position: relative;
    overflow: hidden;
}
        </code>
    </pre>

    <h2>Samples</h2>
    <p>In this section you will find different Samples covering different use cases we have in our web applications.</p>
    @{
        Html.RenderPartial(
            "Demos/_IScrollDemos",
            Render<ControllerDemoCollection>
                .Model(Model)
                .As(ERender.Content));
    }
</div>

Scrolltopia.Web/Views/Iscroll/InteractiveScrollbar.cshtml
@{
    ViewBag.Title = "Interactive scrollbar | iScroll";
}


<div class="container">
    <div class="row">
        <h1>Interactive Scrollbar</h1>
        <p>
            This sample displays a scrollbar which is draggable.
        </p>
    </div>
    <div class="row">

        <section class="sample">

            <div class="iscroll-container">
                <p class="height-of-450-pixels">I should scroll</p>
            </div>

        </section>

    </div>
    <div class="row">
        <h2>Configuration</h2>
        <pre>
            {
                scrollbars: true,
                interactiveScrollbars: true,
                mouseWheel: true
            }   
        </pre>
    </div>
</div>

@section Script
{
    <script type="text/javascript">
        (function () {
            'use strict';

            var myscroll = new IScroll('.iscroll-container', {
                scrollbars: true,
                interactiveScrollbars: true,
                mouseWheel: true
            });
        }());
     </script>
}

Scrolltopia.Web/Views/Iscroll/MinimalSetup.cshtml
@{
    ViewBag.Title = "Minimal | iScroll";
}

<div class="container">
    <div class="row">
        <h1>Minimal sample</h1>
        <p>
            This sample has no scrollbar. It just can be dragged up and down to scroll
        </p>

        <div class="alert alert-warning">
            <span class="glyphicon glyphicon-warning-sign"></span> iScroll prevents you from selecting the text inside the scrolling-container.
        </div>
    </div>
    <div class="row">

        <section class="sample">

            <div class="iscroll-container">
                <div class="height-of-450-pixels">
                    @LoremIpsum.InsertParagraphs(1)
                </div>
            </div>

        </section>

    </div>
</div>

@section Script
{
    <script type="text/javascript">
        (function() {
            'use strict';

            var myscroll = new IScroll('.iscroll-container');
        }());
    </script>
}

Scrolltopia.Web/Views/Iscroll/ResizingContainer.cshtml
@{
    ViewBag.Title = "Resizing container | iScroll";
}


<div class="container">
    <div class="row">
        <h1>Resizing container</h1>
        <p>
            This sample uses shows the usage of <code>refresh()</code> triggering iScroll to calculate a new scrollbar.
        </p>
    </div>
    <div class="row">
        <button class="btn btn-primary" id="btn-change-height">Change height</button>
        <hr>
    </div>
    <div class="row">

        <section class="sample">

            <div class="iscroll-container ">
                <p class="height-of-450-pixels">I should scroll</p>
            </div>

        </section>
        
    </div>
    <div class="row">
        <h2>Configuration</h2>
        <pre>
            {
                scrollbars: true,
                mouseWheel: true
            }   
        </pre>

        <h2>Other</h2>
        <pre>
            // refresh after height changed
            myScroll.refresh();
        </pre>
    </div>
</div>

@section Script
{
    <script type="text/javascript">
        (function () {
            'use strict';

            var myScroll = new IScroll('.iscroll-container', {
                scrollbars: true,
                mouseWheel: true
            });


            $('#btn-change-height').on('click', function() {

                $('.iscroll-container').toggleClass('iscroll-container-400px');
                myScroll.refresh();

            });
        }());
     </script>
}

Scrolltopia.Web/Views/Iscroll/ResizingScrollingContent.cshtml
@{
    ViewBag.Title = "Resizing scrolling content | iScroll";
}


<div class="container">
    <div class="row">
        <h1>Resizing scrolling content</h1>
        <p>
            IScroll's <code>refresh()</code> also works when the scrolling-content has changed.
        </p>
        <div class="alert alert-warning">
            <strong>Behavior!</strong>
            <code>new IScroll('iscroll-container')</code> just defines the wrapper for scrolling. IScroll will automatically fetch the first child and will make it srollable.
            That's why a inner container is introduced in this sample <code>"scrolling-content"</code>.
        </div>
    </div>
    <div class="row">
        <button class="btn btn-primary" id="btn-resize-scrolling-content">Resize scrolling content</button>
        <hr>
    </div>
    <div class="row">

        <section class="sample">

            <div class="iscroll-container">
                <div class="scrolling-content">
                    @LoremIpsum.InsertParagraphs(2)
                    <p id="p_empty"></p>
                </div>
            </div>

        </section>
        
    </div>
    <div class="row">
        <h2>Configuration</h2>
        <pre>
            {
                scrollbars: true,
                mouseWheel: true
            }   
        </pre>

        <h2>Other</h2>
        <pre>
            // refresh after height changed
            myScroll.refresh();
        </pre>
    </div>
</div>

@section Script
{
    <script type="text/javascript">
        (function () {
            'use strict';

            var myScroll = new IScroll('.iscroll-container', {
                scrollbars: true,
                mouseWheel: true
            });


            $('#btn-resize-scrolling-content').on('click', function () {

                $('#p_empty').toggleClass('mdr-tower');
                myScroll.refresh();

            });
        }());
     </script>
}

Scrolltopia.Web/Views/Iscroll/Scrollbar.cshtml
@{
    ViewBag.Title = "Scrollbar | iScroll";
}

<div class="container">
    <div class="row">
        <h1>Scrollbar</h1>
        <p>
            This sample adds a scrollbar and enables scrolling with the mouse whell.
        </p>
    </div>
    <div class="row">

        <section class="sample">

            <div class="iscroll-container">
                <p class="height-of-450-pixels">I should scroll</p>
            </div>

        </section>

    </div>
    <div class="row">
        <h2>Configuration</h2>
        <pre>
            {
                scrollbars: true,
                mouseWheel: true
            }   
        </pre>
    </div>
</div>

@section Script
{
    <script type="text/javascript">
        (function () {
            'use strict';

            var myscroll = new IScroll('.iscroll-container', {
                mouseWheel: true,
                scrollbars: true
            });
        }());
     </script>
}

Scrolltopia.Web/Views/Iscroll/ShrinkedScrollbar.cshtml
@{
    ViewBag.Title = "Shrinked scrollbar | iScroll";
}


<div class="container">
    <div class="row">
        <h1>Shrinked scrollbar</h1>
        <p>
            This sample uses <code>shrinkScrollbars</code> adding an animation when the user scrolls to top or bottom of the container.
        </p>
        <div class="alert alert-warning">
            <span class="glyphicon glyphicon-warning-sign"></span> It seems that this option has no impact when mouse wheel is used.
        </div>

        <hr>
    </div>
    <div class="row">

        <section class="sample">

            <div class="iscroll-container clipped ">
                <p class="height-of-450-pixels">I should scroll</p>
            </div>

        </section>

        <hr>

        <section class="sample">

            <div class="iscroll-container scaled">
                <p class="height-of-450-pixels">I should scroll</p>
            </div>

        </section>

    </div>
    <div class="row">
        <h2>Configuration</h2>
        <pre>
            {
                scrollbars: true,
                shrinkScrollbars: 'clip' || 'scale',
                mouseWheel: true
            }   
        </pre>
    </div>
</div>

@section Script
{
    <script type="text/javascript">
        (function () {
            'use strict';

            var clippedScroll = new IScroll('.iscroll-container.clipped', {
                scrollbars: true,
                shrinkScrollbars: 'clip',
                mouseWheel: true
            });

            var scaledScroll = new IScroll('.iscroll-container.scaled', {
                scrollbars: true,
                shrinkScrollbars: 'scale',
                mouseWheel: true
            });
        }());
     </script>
}

Scrolltopia.Web/Views/Iscroll/TriggeringControls.cshtml
@{
    ViewBag.Title = "Triggering controls | iScroll";
}


<div class="container">
    <div class="row">
        <h1>Triggering controls</h1>
        <div>
            In this sample scrolling can be controled by clicking buttons.
                <code>scrollBy(x, y, time, ease)</code> is used to scroll relative to the current position.
                <code>IScroll.utils.ease</code> namespace provides <i>4</i> different kinds of scroll animations.
                <ul>
                    <li>quadratic</li>
                    <li>ciruclar</li>
                    <li>back</li>
                    <li>bounce</li>
                    <li>elastic</li>
                </ul>
        </div>

        <div class="alert alert-info">
            <span class="glyphicon glyphicon-info-sign"></span> There is also a method called <code>scrollTo(x, y, time, ease)</code> which scrolls absolute to the given coordinates.
        </div>

        <hr>
    </div>

    <div class="row">

        <div class="col-lg-11 col-md-11 col-sm-11 col-xs-11">

            <section class="sample">

                <div class="iscroll-container">
                    <div class="scrolling-content">
                        @LoremIpsum.InsertParagraphs(4)
                    </div>
                </div>

            </section>
        </div>

        <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
            <div class="btn-group-vertical" role="group" aria-label="scroll-controls">
                <button id="btn-scroll-up" class="btn btn-primary"><span class="glyphicon glyphicon-arrow-up"></span></button>
                <button id="btn-scroll-down" class="btn btn-primary"><span class="glyphicon glyphicon-arrow-down"></span></button>
            </div>
        </div>
    </div>
    <div class="row">
        <h2>Configuration</h2>
        <pre>
            {
                scrollbars: true,
                interactiveScrollbars: true,
                mouseWheel: true
            }   
        </pre>
    </div>
</div>

@section Script
{
    <script type="text/javascript">
        (function () {
            'use strict';

            var myScroll = new IScroll('.iscroll-container', {
                scrollbars: true,
                interactiveScrollbars: true,
                mouseWheel: true
            });

            var up = $('#btn-scroll-up');
            var down = $('#btn-scroll-down');

            up.on('click', function () {
                myScroll.scrollBy(0, 50, 200, IScroll.utils.ease.quadratic);
            });

            down.on('click', function () {
                myScroll.scrollBy(0, -50, 200, IScroll.utils.ease.quadratic);
            });

        }());
     </script>
}

Scrolltopia.Web/Views/NanoScroller/Index.cshtml
@using Scrolltopia.Web.Models
@using Scrolltopia.Web.ViewModels
@model ControllerDemoCollection

@{
    ViewBag.Title = "nanoScroller | Scrolltopia";
}

<div class="container">
    <h1>
        NanoScroller showcase
        <small>
            <a href="https://github.com/jamesflorentino/nanoScrollerJS" target="_blank">Project site</a> | <a href="https://jamesflorentino.github.io/nanoScrollerJS/">Demo</a>
        </small>
    </h1>

    <h2 id="no-ie8-support">No IE8 support</h2>
    <div class="alert alert-warning">
        <span class="glyphicon glyphicon-warning-sign"></span>&nbsp;
        It turns out taht iScroll does not support IE8 (<a href="https://github.com/cubiq/iscroll/pull/436" target="_blank">see issue</a>).
        There are some libraries hacking the support for IE8.
        Trying <a href="https://github.com/4alexandr/iscroll5-ie8/blob/master/iscroll5-ie8.js">iscroll5-ie8</a> does not work.
    </div>

    <h2>Prerequisits</h2>
    <div>
        To get iScroll to work it is importand to setup some css styles. Otherwise you will experience an unexpected scrolling behavior.
        The following sample shows the style of the wrapping container which will be passed to iScroll.
        <ul>
            <li>The container has to define <code>height</code> or <code>max-height</code>.</li>
            <li><code>overflow:hidden</code> has to be set.</li>
            <li>The container needs to have <code>postion-relative</code>.</li>
        </ul>
    </div>
    <pre class="reset-styles">
    <code class="css">
.iscroll-container {
    height:   200px;
    position: relative;
    overflow: hidden;
}
        </code>
    </pre>

    <h2>Samples</h2>
    <p>In this section you will find different Samples covering different use cases we have in our web applications.</p>
    @{
        Html.RenderPartial(
            "Demos/_IScrollDemos",
            Render<ControllerDemoCollection>
                .Model(Model)
                .As(ERender.Content));
    }
</div>